### ISSUE TITLE
lrange failure

### ISSUE THREAD

**Issue by dengcb** [edtechd/phpredis#12]
I change from php 5.5 to 7, and redis can't use lrange function.
The result is null.

**Comment by Sean-Der** [comment]
Hey @dengcb would you mind trying out my PR [here](https://github.com/phpredis/phpredis/pull/654)

**Comment by dc769319** [comment]
Maybe you can use stream_socket_client connect to redis server directly, and execute redis command like using redis-cli. refer Yii2  yii\redis\Connection
