### ISSUE TITLE
Multiple efforts to get a PHP 7 version

### ISSUE THREAD

**Issue by Sean-Der** [edtechd/phpredis#13]
Hey!

I have been working on porting this as well, and didn't see you and @laruence had already been working on this.

I have [this](https://github.com/Sean-Der/phpredis/tree/php7-new) branch which is against the develop branch and currently compiles, but am working on fixing test fails. How can we make this so we all work together?

thanks!

**Comment by Sean-Der** [comment]
We _probably_ should take @laruence's work, I can work on fixing tests fails etc.. if we decide that

**Comment by Jerry-Shaw** [comment]
They may be busy for days, but glad to see you come to work on this.
I could only help with testing, because I don't know C.

**Comment by Sean-Der** [comment]
Hey @Jerry-Shaw !

Since I haven't gotten a response I am just gonna go ahead and keep working on my fork, worse case scenario I can just throw my work away.

Would you mind banging on [my fork](https://github.com/Sean-Der/phpredis/tree/php7-new) ? I will be fixing issues as they come in, thanks!

**Comment by Jerry-Shaw** [comment]
Hi, @Sean-Der .

Yep, I am glad to help if you needed. 

I have been watching this PR on PHP7 for a long time since PHP 7 was announced. This extension keeps my little search engine working, and I am looking forward to changing PHP5 totally to PHP7.

Sadly, I don't know C, so I can only help with testing. Using windows, better to have compiled binary, or I'll try to compile it with VS2015 as well. But once I get error when compiling, I cannot fix it at all... I may need help too, haha.

**Comment by laruence** [comment]
@Sean-Der I got troubles try to merge the new commits from the official repo phpredis/phpredis https://github.com/phpredis/phpredis .. maybe you can have a look

**Comment by edtechd** [comment]
Hi Sean,

I am also not working now on this project. So, if you want we can try to merge our repositories (or you can make pull requests of the tested changes there).

**Comment by Sean-Der** [comment]
Hey @edtechd @Jerry-Shaw @laruence 

Sorry about the duplicated work, but I have a version [here](https://github.com/phpredis/phpredis/pull/654) that passes the entire test suite. I am working on fixing compiler warnings + leaks now.

If you have any time would you mind testing it, and if anything comes up I am actively working and will be adding more tests cases.

**Comment by Jerry-Shaw** [comment]
@Sean-Der , I've just compiled one from the php7-new branch against PHP7 RC2, and test it in my search engine. It makes PHP7 CGI crashed anyhow, and I'm still looking for the redis functions which caused this.

**Comment by Jerry-Shaw** [comment]
@Sean-Der , here is the function I found out which may cause crashed: zRevRange.
And zInter, zCard, zUnion seem not not functional at all on my PC.

**Comment by Sean-Der** [comment]
Bad news @Jerry-Shaw, all of these already have tests and I am not able to see what is causing issues for you :(

Could I get a snippet that reproduces the segfault/bugs ? I will update the tests to include your fail cases. thanks!

**Comment by Jerry-Shaw** [comment]
I'll test it again and give you my script tomorrow after re-ensured.
