### ISSUE TITLE
Another problem on session in redis

### ISSUE THREAD

**Issue by Jerry-Shaw** [edtechd/phpredis#7]
Hi, Jan & edtechd.

When I am going to use redis to store session with the php_redis.dll in PHP7, with the script below,

ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://localhost:6379');
// OR this one: ini_set('session.save_path', 'tcp://127.0.0.1:6379');

session_start();

$_SESSION['a']='a';
// OR more session setting codes...

it may be ok in the first time running the script, if redis doesn't store the session value. But it always makes php-cgi crashed when simplely refresh the page or start the session function even using the script below,

ini_set('session.save_handler', 'redis');
ini_set('session.save_path', 'tcp://localhost:6379');

session_start();

// no session operations

The FastCGI crashed.

And, thanks again to reply.

**Comment by edtechd** [comment]
Hi Jerry, I have updated the code and it doesn't crash now for me. Could you please check?

**Comment by Jerry-Shaw** [comment]
Thanks edtechd. I may be busy coding a lot of web pages in a few days, I'll check it later when Jan-E compiles it out. And hopefully, you could fix #5, thanks again.

**Comment by Jan-E** [comment]
https://www.apachelounge.com/viewtopic.php?p=31043#31043

**Comment by Jerry-Shaw** [comment]
Thanks, guys. I'll test it tomorrow.

**Comment by Jerry-Shaw** [comment]
Tested, session function works OK now.

**Comment by Jerry-Shaw** [comment]
Hi, @Jan-E 

The php_redis.dll from your pack of php7-beta1 is not compatible with the official pack of php7-beta1, it makes the official php crashed when loading. I compiled a new one based on the official php-sdk, and it works. There must be changes in the php7 source codes.

**Comment by Jan-E** [comment]
There were a lot of last-minute changes in the PHP7-sources:
https://github.com/php/php-src/commits/PHP-7.0.0

Last Friday I recompiled my builds as well. If you had an earlier download, that would explain it. Could you try again to verify this?

**Comment by Jerry-Shaw** [comment]
@Jan-E , Yep, you are right. It works now.
